COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
MOUSEKEY_ENABLE = no
VIA_ENABLE = no
VIAL_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
LTO_ENABLE = yes
